# test yaml

model_name: "osp_next"
pipeline_name: "t2v"
seed: 1024

prompt_txt: "assets/t2v/MovieGenVideoBench_rewritten.txt"
output_dir: "samples/osp_next_14b_81f720p_sparse2d2_ssp4/iter_000010000_ema"

num_frames: 81
height: 720
width: 1280
save_fps: 16
batch_size: 1

fsdp_size: 8
cp_size: 2
skiparse_cp_size: 4
use_context_parallel: False
use_skiparse_context_parallel: True
reshard_after_forward: True
explicit_prefetching_num_blocks: 2
weight_dtype: "bf16"
save_with_dcp_api: False

model_config:
  dim: 5120
  ffn_dim: 13824
  freq_dim: 256
  in_dim: 16
  num_heads: 40
  num_layers: 40
  out_dim: 16
  text_len: 512
  skiparse_model_type: "dual_end"
  sparse_ratio: 2
  num_full_blocks: 8
  num_register_tokens: 0
  skiparse_1d: False
  skiparse_2d: True
  pretrained_model_dir_or_checkpoint: "output/osp_next_14b_81f720p_sparse2d2_ssp4/iter_000010000/ema_model_state_dict.pt"

scheduler_config:
  scheduler_name: "flow_matching"
  num_inference_steps: 50
  shift: 7.0
  guidance_scale: 5.0

vae_config:
  vae_path: "Wan2.1-T2V-14B/Wan2.1_VAE.pth"
  dtype: "fp16"

text_encoder_config:
  text_len: 512
  checkpoint_path: "Wan2.1-T2V-14B/models_t5_umt5-xxl-enc-bf16.pth"
  text_tokenizer_path: "Wan2.1-T2V-14B/google/umt5-xxl"
  use_fsdp: True
