# test yaml

model_name: "osp_next"
pipeline_name: "t2v"
seed: 666

output_dir: "samples/vbench/osp_14b_grpo_step148"

num_frames: 81
height: 720
width: 1280
save_fps: 16
batch_size: 1

fsdp_size: 8
cp_size: 2
skiparse_cp_size: 4
use_context_parallel: False
use_skiparse_context_parallel: True
reshard_after_forward: True
explicit_prefetching_num_blocks: 0
weight_dtype: "bf16"
save_with_dcp_api: False

model_config:
  dim: 5120
  ffn_dim: 13824
  freq_dim: 256
  in_dim: 16
  num_heads: 40
  num_layers: 40
  out_dim: 16
  text_len: 512
  skiparse_model_type: "dual_end"
  sparse_ratio: 2
  num_full_blocks: 8
  num_register_tokens: 0
  skiparse_1d: False
  skiparse_2d: True
  pretrained_model_dir_or_checkpoint: "/home/ma-user/work/gyy/TorchDiff/output/osp_next_14b_81f720p_sparse2d2_ssp4/iter_000006000/ema_model_state_dict.pt"

scheduler_config:
  scheduler_name: "flow_matching"
  num_inference_steps: 50
  shift: 7.0
  guidance_scale: 5.0

vae_config:
  vae_path: "/home/ma-user/work/gyy/TorchDiff/Wan2.1-T2V-14B/Wan2.1_VAE.pth"
  dtype: "fp16"

text_encoder_config:
  text_len: 512
  checkpoint_path: "/home/ma-user/work/gyy/TorchDiff/Wan2.1-T2V-14B/models_t5_umt5-xxl-enc-bf16.pth"
  text_tokenizer_path: "/home/ma-user/work/gyy/TorchDiff/Wan2.1-T2V-14B/google/umt5-xxl"
  use_fsdp: True

data_config:
  batch_size: 1
  num_workers: 16
  pin_memory: False
  dataset_name: "t2v_eval"
  dataset_config:
    metafile_or_dir_path: "/home/ma-user/work/gyy/TorchDiff/eval/filtered_samples_946.lmdb"
    text_tokenizer_path: "/home/ma-user/work/gyy/TorchDiff/Wan2.1-T2V-14B/google/umt5-xxl"
    num_samples_per_prompt: 5
    sample_height: 720
    sample_width: 1280
    sample_num_frames: 81
    train_fps: 16
    tokenizer_max_length: 512
    return_prompt_mask: True
  sampler_name: "stateful_distributed"
  collator_name: "t2v_eval"

  lora_path: /home/ma-user/work/xianyi/osp_next/TorchDiff/output/osp_next_14b_lr1e_5_81f720p_sparse2d2_sp2_ssp4_grpo4_node7/lora-checkpoint-148/adapter_model.bin